// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"g_api/libs/weather-lib/ent/forcast"
	"g_api/libs/weather-lib/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ForcastDelete is the builder for deleting a Forcast entity.
type ForcastDelete struct {
	config
	hooks    []Hook
	mutation *ForcastMutation
}

// Where appends a list predicates to the ForcastDelete builder.
func (fd *ForcastDelete) Where(ps ...predicate.Forcast) *ForcastDelete {
	fd.mutation.Where(ps...)
	return fd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fd *ForcastDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ForcastMutation](ctx, fd.sqlExec, fd.mutation, fd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fd *ForcastDelete) ExecX(ctx context.Context) int {
	n, err := fd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fd *ForcastDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(forcast.Table, sqlgraph.NewFieldSpec(forcast.FieldID, field.TypeInt))
	if ps := fd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fd.mutation.done = true
	return affected, err
}

// ForcastDeleteOne is the builder for deleting a single Forcast entity.
type ForcastDeleteOne struct {
	fd *ForcastDelete
}

// Where appends a list predicates to the ForcastDelete builder.
func (fdo *ForcastDeleteOne) Where(ps ...predicate.Forcast) *ForcastDeleteOne {
	fdo.fd.mutation.Where(ps...)
	return fdo
}

// Exec executes the deletion query.
func (fdo *ForcastDeleteOne) Exec(ctx context.Context) error {
	n, err := fdo.fd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{forcast.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fdo *ForcastDeleteOne) ExecX(ctx context.Context) {
	if err := fdo.Exec(ctx); err != nil {
		panic(err)
	}
}
