// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"g_api/libs/weather-lib/ent/forcast"
	"g_api/libs/weather-lib/ent/predicate"
	"g_api/libs/weather-lib/ent/weather"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ForcastUpdate is the builder for updating Forcast entities.
type ForcastUpdate struct {
	config
	hooks    []Hook
	mutation *ForcastMutation
}

// Where appends a list predicates to the ForcastUpdate builder.
func (fu *ForcastUpdate) Where(ps ...predicate.Forcast) *ForcastUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetCountry sets the "country" field.
func (fu *ForcastUpdate) SetCountry(s string) *ForcastUpdate {
	fu.mutation.SetCountry(s)
	return fu
}

// SetRegion sets the "region" field.
func (fu *ForcastUpdate) SetRegion(s string) *ForcastUpdate {
	fu.mutation.SetRegion(s)
	return fu
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (fu *ForcastUpdate) SetNillableRegion(s *string) *ForcastUpdate {
	if s != nil {
		fu.SetRegion(*s)
	}
	return fu
}

// ClearRegion clears the value of the "region" field.
func (fu *ForcastUpdate) ClearRegion() *ForcastUpdate {
	fu.mutation.ClearRegion()
	return fu
}

// SetDate sets the "date" field.
func (fu *ForcastUpdate) SetDate(t time.Time) *ForcastUpdate {
	fu.mutation.SetDate(t)
	return fu
}

// SetLocaltime sets the "localtime" field.
func (fu *ForcastUpdate) SetLocaltime(t time.Time) *ForcastUpdate {
	fu.mutation.SetLocaltime(t)
	return fu
}

// SetNillableLocaltime sets the "localtime" field if the given value is not nil.
func (fu *ForcastUpdate) SetNillableLocaltime(t *time.Time) *ForcastUpdate {
	if t != nil {
		fu.SetLocaltime(*t)
	}
	return fu
}

// ClearLocaltime clears the value of the "localtime" field.
func (fu *ForcastUpdate) ClearLocaltime() *ForcastUpdate {
	fu.mutation.ClearLocaltime()
	return fu
}

// SetIcon sets the "icon" field.
func (fu *ForcastUpdate) SetIcon(s string) *ForcastUpdate {
	fu.mutation.SetIcon(s)
	return fu
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (fu *ForcastUpdate) SetNillableIcon(s *string) *ForcastUpdate {
	if s != nil {
		fu.SetIcon(*s)
	}
	return fu
}

// ClearIcon clears the value of the "icon" field.
func (fu *ForcastUpdate) ClearIcon() *ForcastUpdate {
	fu.mutation.ClearIcon()
	return fu
}

// SetMaxTemp sets the "max_temp" field.
func (fu *ForcastUpdate) SetMaxTemp(f float64) *ForcastUpdate {
	fu.mutation.ResetMaxTemp()
	fu.mutation.SetMaxTemp(f)
	return fu
}

// SetNillableMaxTemp sets the "max_temp" field if the given value is not nil.
func (fu *ForcastUpdate) SetNillableMaxTemp(f *float64) *ForcastUpdate {
	if f != nil {
		fu.SetMaxTemp(*f)
	}
	return fu
}

// AddMaxTemp adds f to the "max_temp" field.
func (fu *ForcastUpdate) AddMaxTemp(f float64) *ForcastUpdate {
	fu.mutation.AddMaxTemp(f)
	return fu
}

// SetMinTemp sets the "min_temp" field.
func (fu *ForcastUpdate) SetMinTemp(f float64) *ForcastUpdate {
	fu.mutation.ResetMinTemp()
	fu.mutation.SetMinTemp(f)
	return fu
}

// SetNillableMinTemp sets the "min_temp" field if the given value is not nil.
func (fu *ForcastUpdate) SetNillableMinTemp(f *float64) *ForcastUpdate {
	if f != nil {
		fu.SetMinTemp(*f)
	}
	return fu
}

// AddMinTemp adds f to the "min_temp" field.
func (fu *ForcastUpdate) AddMinTemp(f float64) *ForcastUpdate {
	fu.mutation.AddMinTemp(f)
	return fu
}

// SetAvgTemp sets the "avg_temp" field.
func (fu *ForcastUpdate) SetAvgTemp(f float64) *ForcastUpdate {
	fu.mutation.ResetAvgTemp()
	fu.mutation.SetAvgTemp(f)
	return fu
}

// SetNillableAvgTemp sets the "avg_temp" field if the given value is not nil.
func (fu *ForcastUpdate) SetNillableAvgTemp(f *float64) *ForcastUpdate {
	if f != nil {
		fu.SetAvgTemp(*f)
	}
	return fu
}

// AddAvgTemp adds f to the "avg_temp" field.
func (fu *ForcastUpdate) AddAvgTemp(f float64) *ForcastUpdate {
	fu.mutation.AddAvgTemp(f)
	return fu
}

// AddWeatherIDs adds the "weather" edge to the Weather entity by IDs.
func (fu *ForcastUpdate) AddWeatherIDs(ids ...int) *ForcastUpdate {
	fu.mutation.AddWeatherIDs(ids...)
	return fu
}

// AddWeather adds the "weather" edges to the Weather entity.
func (fu *ForcastUpdate) AddWeather(w ...*Weather) *ForcastUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return fu.AddWeatherIDs(ids...)
}

// Mutation returns the ForcastMutation object of the builder.
func (fu *ForcastUpdate) Mutation() *ForcastMutation {
	return fu.mutation
}

// ClearWeather clears all "weather" edges to the Weather entity.
func (fu *ForcastUpdate) ClearWeather() *ForcastUpdate {
	fu.mutation.ClearWeather()
	return fu
}

// RemoveWeatherIDs removes the "weather" edge to Weather entities by IDs.
func (fu *ForcastUpdate) RemoveWeatherIDs(ids ...int) *ForcastUpdate {
	fu.mutation.RemoveWeatherIDs(ids...)
	return fu
}

// RemoveWeather removes "weather" edges to Weather entities.
func (fu *ForcastUpdate) RemoveWeather(w ...*Weather) *ForcastUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return fu.RemoveWeatherIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *ForcastUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ForcastMutation](ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *ForcastUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *ForcastUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *ForcastUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *ForcastUpdate) check() error {
	if v, ok := fu.mutation.Country(); ok {
		if err := forcast.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Forcast.country": %w`, err)}
		}
	}
	return nil
}

func (fu *ForcastUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(forcast.Table, forcast.Columns, sqlgraph.NewFieldSpec(forcast.FieldID, field.TypeInt))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Country(); ok {
		_spec.SetField(forcast.FieldCountry, field.TypeString, value)
	}
	if value, ok := fu.mutation.Region(); ok {
		_spec.SetField(forcast.FieldRegion, field.TypeString, value)
	}
	if fu.mutation.RegionCleared() {
		_spec.ClearField(forcast.FieldRegion, field.TypeString)
	}
	if value, ok := fu.mutation.Date(); ok {
		_spec.SetField(forcast.FieldDate, field.TypeTime, value)
	}
	if value, ok := fu.mutation.Localtime(); ok {
		_spec.SetField(forcast.FieldLocaltime, field.TypeTime, value)
	}
	if fu.mutation.LocaltimeCleared() {
		_spec.ClearField(forcast.FieldLocaltime, field.TypeTime)
	}
	if value, ok := fu.mutation.Icon(); ok {
		_spec.SetField(forcast.FieldIcon, field.TypeString, value)
	}
	if fu.mutation.IconCleared() {
		_spec.ClearField(forcast.FieldIcon, field.TypeString)
	}
	if value, ok := fu.mutation.MaxTemp(); ok {
		_spec.SetField(forcast.FieldMaxTemp, field.TypeFloat64, value)
	}
	if value, ok := fu.mutation.AddedMaxTemp(); ok {
		_spec.AddField(forcast.FieldMaxTemp, field.TypeFloat64, value)
	}
	if value, ok := fu.mutation.MinTemp(); ok {
		_spec.SetField(forcast.FieldMinTemp, field.TypeFloat64, value)
	}
	if value, ok := fu.mutation.AddedMinTemp(); ok {
		_spec.AddField(forcast.FieldMinTemp, field.TypeFloat64, value)
	}
	if value, ok := fu.mutation.AvgTemp(); ok {
		_spec.SetField(forcast.FieldAvgTemp, field.TypeFloat64, value)
	}
	if value, ok := fu.mutation.AddedAvgTemp(); ok {
		_spec.AddField(forcast.FieldAvgTemp, field.TypeFloat64, value)
	}
	if fu.mutation.WeatherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   forcast.WeatherTable,
			Columns: []string{forcast.WeatherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weather.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.RemovedWeatherIDs(); len(nodes) > 0 && !fu.mutation.WeatherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   forcast.WeatherTable,
			Columns: []string{forcast.WeatherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weather.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.WeatherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   forcast.WeatherTable,
			Columns: []string{forcast.WeatherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weather.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{forcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// ForcastUpdateOne is the builder for updating a single Forcast entity.
type ForcastUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ForcastMutation
}

// SetCountry sets the "country" field.
func (fuo *ForcastUpdateOne) SetCountry(s string) *ForcastUpdateOne {
	fuo.mutation.SetCountry(s)
	return fuo
}

// SetRegion sets the "region" field.
func (fuo *ForcastUpdateOne) SetRegion(s string) *ForcastUpdateOne {
	fuo.mutation.SetRegion(s)
	return fuo
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (fuo *ForcastUpdateOne) SetNillableRegion(s *string) *ForcastUpdateOne {
	if s != nil {
		fuo.SetRegion(*s)
	}
	return fuo
}

// ClearRegion clears the value of the "region" field.
func (fuo *ForcastUpdateOne) ClearRegion() *ForcastUpdateOne {
	fuo.mutation.ClearRegion()
	return fuo
}

// SetDate sets the "date" field.
func (fuo *ForcastUpdateOne) SetDate(t time.Time) *ForcastUpdateOne {
	fuo.mutation.SetDate(t)
	return fuo
}

// SetLocaltime sets the "localtime" field.
func (fuo *ForcastUpdateOne) SetLocaltime(t time.Time) *ForcastUpdateOne {
	fuo.mutation.SetLocaltime(t)
	return fuo
}

// SetNillableLocaltime sets the "localtime" field if the given value is not nil.
func (fuo *ForcastUpdateOne) SetNillableLocaltime(t *time.Time) *ForcastUpdateOne {
	if t != nil {
		fuo.SetLocaltime(*t)
	}
	return fuo
}

// ClearLocaltime clears the value of the "localtime" field.
func (fuo *ForcastUpdateOne) ClearLocaltime() *ForcastUpdateOne {
	fuo.mutation.ClearLocaltime()
	return fuo
}

// SetIcon sets the "icon" field.
func (fuo *ForcastUpdateOne) SetIcon(s string) *ForcastUpdateOne {
	fuo.mutation.SetIcon(s)
	return fuo
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (fuo *ForcastUpdateOne) SetNillableIcon(s *string) *ForcastUpdateOne {
	if s != nil {
		fuo.SetIcon(*s)
	}
	return fuo
}

// ClearIcon clears the value of the "icon" field.
func (fuo *ForcastUpdateOne) ClearIcon() *ForcastUpdateOne {
	fuo.mutation.ClearIcon()
	return fuo
}

// SetMaxTemp sets the "max_temp" field.
func (fuo *ForcastUpdateOne) SetMaxTemp(f float64) *ForcastUpdateOne {
	fuo.mutation.ResetMaxTemp()
	fuo.mutation.SetMaxTemp(f)
	return fuo
}

// SetNillableMaxTemp sets the "max_temp" field if the given value is not nil.
func (fuo *ForcastUpdateOne) SetNillableMaxTemp(f *float64) *ForcastUpdateOne {
	if f != nil {
		fuo.SetMaxTemp(*f)
	}
	return fuo
}

// AddMaxTemp adds f to the "max_temp" field.
func (fuo *ForcastUpdateOne) AddMaxTemp(f float64) *ForcastUpdateOne {
	fuo.mutation.AddMaxTemp(f)
	return fuo
}

// SetMinTemp sets the "min_temp" field.
func (fuo *ForcastUpdateOne) SetMinTemp(f float64) *ForcastUpdateOne {
	fuo.mutation.ResetMinTemp()
	fuo.mutation.SetMinTemp(f)
	return fuo
}

// SetNillableMinTemp sets the "min_temp" field if the given value is not nil.
func (fuo *ForcastUpdateOne) SetNillableMinTemp(f *float64) *ForcastUpdateOne {
	if f != nil {
		fuo.SetMinTemp(*f)
	}
	return fuo
}

// AddMinTemp adds f to the "min_temp" field.
func (fuo *ForcastUpdateOne) AddMinTemp(f float64) *ForcastUpdateOne {
	fuo.mutation.AddMinTemp(f)
	return fuo
}

// SetAvgTemp sets the "avg_temp" field.
func (fuo *ForcastUpdateOne) SetAvgTemp(f float64) *ForcastUpdateOne {
	fuo.mutation.ResetAvgTemp()
	fuo.mutation.SetAvgTemp(f)
	return fuo
}

// SetNillableAvgTemp sets the "avg_temp" field if the given value is not nil.
func (fuo *ForcastUpdateOne) SetNillableAvgTemp(f *float64) *ForcastUpdateOne {
	if f != nil {
		fuo.SetAvgTemp(*f)
	}
	return fuo
}

// AddAvgTemp adds f to the "avg_temp" field.
func (fuo *ForcastUpdateOne) AddAvgTemp(f float64) *ForcastUpdateOne {
	fuo.mutation.AddAvgTemp(f)
	return fuo
}

// AddWeatherIDs adds the "weather" edge to the Weather entity by IDs.
func (fuo *ForcastUpdateOne) AddWeatherIDs(ids ...int) *ForcastUpdateOne {
	fuo.mutation.AddWeatherIDs(ids...)
	return fuo
}

// AddWeather adds the "weather" edges to the Weather entity.
func (fuo *ForcastUpdateOne) AddWeather(w ...*Weather) *ForcastUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return fuo.AddWeatherIDs(ids...)
}

// Mutation returns the ForcastMutation object of the builder.
func (fuo *ForcastUpdateOne) Mutation() *ForcastMutation {
	return fuo.mutation
}

// ClearWeather clears all "weather" edges to the Weather entity.
func (fuo *ForcastUpdateOne) ClearWeather() *ForcastUpdateOne {
	fuo.mutation.ClearWeather()
	return fuo
}

// RemoveWeatherIDs removes the "weather" edge to Weather entities by IDs.
func (fuo *ForcastUpdateOne) RemoveWeatherIDs(ids ...int) *ForcastUpdateOne {
	fuo.mutation.RemoveWeatherIDs(ids...)
	return fuo
}

// RemoveWeather removes "weather" edges to Weather entities.
func (fuo *ForcastUpdateOne) RemoveWeather(w ...*Weather) *ForcastUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return fuo.RemoveWeatherIDs(ids...)
}

// Where appends a list predicates to the ForcastUpdate builder.
func (fuo *ForcastUpdateOne) Where(ps ...predicate.Forcast) *ForcastUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *ForcastUpdateOne) Select(field string, fields ...string) *ForcastUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Forcast entity.
func (fuo *ForcastUpdateOne) Save(ctx context.Context) (*Forcast, error) {
	return withHooks[*Forcast, ForcastMutation](ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *ForcastUpdateOne) SaveX(ctx context.Context) *Forcast {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *ForcastUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *ForcastUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *ForcastUpdateOne) check() error {
	if v, ok := fuo.mutation.Country(); ok {
		if err := forcast.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Forcast.country": %w`, err)}
		}
	}
	return nil
}

func (fuo *ForcastUpdateOne) sqlSave(ctx context.Context) (_node *Forcast, err error) {
	if err := fuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(forcast.Table, forcast.Columns, sqlgraph.NewFieldSpec(forcast.FieldID, field.TypeInt))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Forcast.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, forcast.FieldID)
		for _, f := range fields {
			if !forcast.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != forcast.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Country(); ok {
		_spec.SetField(forcast.FieldCountry, field.TypeString, value)
	}
	if value, ok := fuo.mutation.Region(); ok {
		_spec.SetField(forcast.FieldRegion, field.TypeString, value)
	}
	if fuo.mutation.RegionCleared() {
		_spec.ClearField(forcast.FieldRegion, field.TypeString)
	}
	if value, ok := fuo.mutation.Date(); ok {
		_spec.SetField(forcast.FieldDate, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.Localtime(); ok {
		_spec.SetField(forcast.FieldLocaltime, field.TypeTime, value)
	}
	if fuo.mutation.LocaltimeCleared() {
		_spec.ClearField(forcast.FieldLocaltime, field.TypeTime)
	}
	if value, ok := fuo.mutation.Icon(); ok {
		_spec.SetField(forcast.FieldIcon, field.TypeString, value)
	}
	if fuo.mutation.IconCleared() {
		_spec.ClearField(forcast.FieldIcon, field.TypeString)
	}
	if value, ok := fuo.mutation.MaxTemp(); ok {
		_spec.SetField(forcast.FieldMaxTemp, field.TypeFloat64, value)
	}
	if value, ok := fuo.mutation.AddedMaxTemp(); ok {
		_spec.AddField(forcast.FieldMaxTemp, field.TypeFloat64, value)
	}
	if value, ok := fuo.mutation.MinTemp(); ok {
		_spec.SetField(forcast.FieldMinTemp, field.TypeFloat64, value)
	}
	if value, ok := fuo.mutation.AddedMinTemp(); ok {
		_spec.AddField(forcast.FieldMinTemp, field.TypeFloat64, value)
	}
	if value, ok := fuo.mutation.AvgTemp(); ok {
		_spec.SetField(forcast.FieldAvgTemp, field.TypeFloat64, value)
	}
	if value, ok := fuo.mutation.AddedAvgTemp(); ok {
		_spec.AddField(forcast.FieldAvgTemp, field.TypeFloat64, value)
	}
	if fuo.mutation.WeatherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   forcast.WeatherTable,
			Columns: []string{forcast.WeatherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weather.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.RemovedWeatherIDs(); len(nodes) > 0 && !fuo.mutation.WeatherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   forcast.WeatherTable,
			Columns: []string{forcast.WeatherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weather.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.WeatherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   forcast.WeatherTable,
			Columns: []string{forcast.WeatherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weather.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Forcast{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{forcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
