// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"g_api/libs/weather-lib/ent/forcast"
	"g_api/libs/weather-lib/ent/predicate"
	"g_api/libs/weather-lib/ent/weather"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ForcastQuery is the builder for querying Forcast entities.
type ForcastQuery struct {
	config
	ctx         *QueryContext
	order       []OrderFunc
	inters      []Interceptor
	predicates  []predicate.Forcast
	withWeather *WeatherQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ForcastQuery builder.
func (fq *ForcastQuery) Where(ps ...predicate.Forcast) *ForcastQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *ForcastQuery) Limit(limit int) *ForcastQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *ForcastQuery) Offset(offset int) *ForcastQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *ForcastQuery) Unique(unique bool) *ForcastQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *ForcastQuery) Order(o ...OrderFunc) *ForcastQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryWeather chains the current query on the "weather" edge.
func (fq *ForcastQuery) QueryWeather() *WeatherQuery {
	query := (&WeatherClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(forcast.Table, forcast.FieldID, selector),
			sqlgraph.To(weather.Table, weather.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, forcast.WeatherTable, forcast.WeatherColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Forcast entity from the query.
// Returns a *NotFoundError when no Forcast was found.
func (fq *ForcastQuery) First(ctx context.Context) (*Forcast, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{forcast.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *ForcastQuery) FirstX(ctx context.Context) *Forcast {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Forcast ID from the query.
// Returns a *NotFoundError when no Forcast ID was found.
func (fq *ForcastQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{forcast.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *ForcastQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Forcast entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Forcast entity is found.
// Returns a *NotFoundError when no Forcast entities are found.
func (fq *ForcastQuery) Only(ctx context.Context) (*Forcast, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{forcast.Label}
	default:
		return nil, &NotSingularError{forcast.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *ForcastQuery) OnlyX(ctx context.Context) *Forcast {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Forcast ID in the query.
// Returns a *NotSingularError when more than one Forcast ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *ForcastQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{forcast.Label}
	default:
		err = &NotSingularError{forcast.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *ForcastQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Forcasts.
func (fq *ForcastQuery) All(ctx context.Context) ([]*Forcast, error) {
	ctx = setContextOp(ctx, fq.ctx, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Forcast, *ForcastQuery]()
	return withInterceptors[[]*Forcast](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *ForcastQuery) AllX(ctx context.Context) []*Forcast {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Forcast IDs.
func (fq *ForcastQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fq.ctx.Unique == nil && fq.path != nil {
		fq.Unique(true)
	}
	ctx = setContextOp(ctx, fq.ctx, "IDs")
	if err = fq.Select(forcast.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *ForcastQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *ForcastQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*ForcastQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *ForcastQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *ForcastQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *ForcastQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ForcastQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *ForcastQuery) Clone() *ForcastQuery {
	if fq == nil {
		return nil
	}
	return &ForcastQuery{
		config:      fq.config,
		ctx:         fq.ctx.Clone(),
		order:       append([]OrderFunc{}, fq.order...),
		inters:      append([]Interceptor{}, fq.inters...),
		predicates:  append([]predicate.Forcast{}, fq.predicates...),
		withWeather: fq.withWeather.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithWeather tells the query-builder to eager-load the nodes that are connected to
// the "weather" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *ForcastQuery) WithWeather(opts ...func(*WeatherQuery)) *ForcastQuery {
	query := (&WeatherClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withWeather = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Forcast.Query().
//		GroupBy(forcast.FieldCountry).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *ForcastQuery) GroupBy(field string, fields ...string) *ForcastGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ForcastGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = forcast.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//	}
//
//	client.Forcast.Query().
//		Select(forcast.FieldCountry).
//		Scan(ctx, &v)
func (fq *ForcastQuery) Select(fields ...string) *ForcastSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &ForcastSelect{ForcastQuery: fq}
	sbuild.label = forcast.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ForcastSelect configured with the given aggregations.
func (fq *ForcastQuery) Aggregate(fns ...AggregateFunc) *ForcastSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *ForcastQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !forcast.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *ForcastQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Forcast, error) {
	var (
		nodes       = []*Forcast{}
		_spec       = fq.querySpec()
		loadedTypes = [1]bool{
			fq.withWeather != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Forcast).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Forcast{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withWeather; query != nil {
		if err := fq.loadWeather(ctx, query, nodes,
			func(n *Forcast) { n.Edges.Weather = []*Weather{} },
			func(n *Forcast, e *Weather) { n.Edges.Weather = append(n.Edges.Weather, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *ForcastQuery) loadWeather(ctx context.Context, query *WeatherQuery, nodes []*Forcast, init func(*Forcast), assign func(*Forcast, *Weather)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Forcast)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Weather(func(s *sql.Selector) {
		s.Where(sql.InValues(forcast.WeatherColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.forcast_weather
		if fk == nil {
			return fmt.Errorf(`foreign-key "forcast_weather" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "forcast_weather" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fq *ForcastQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *ForcastQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(forcast.Table, forcast.Columns, sqlgraph.NewFieldSpec(forcast.FieldID, field.TypeInt))
	_spec.From = fq.sql
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fq.path != nil {
		_spec.Unique = true
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, forcast.FieldID)
		for i := range fields {
			if fields[i] != forcast.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *ForcastQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(forcast.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = forcast.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForcastGroupBy is the group-by builder for Forcast entities.
type ForcastGroupBy struct {
	selector
	build *ForcastQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *ForcastGroupBy) Aggregate(fns ...AggregateFunc) *ForcastGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *ForcastGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ForcastQuery, *ForcastGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *ForcastGroupBy) sqlScan(ctx context.Context, root *ForcastQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ForcastSelect is the builder for selecting fields of Forcast entities.
type ForcastSelect struct {
	*ForcastQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *ForcastSelect) Aggregate(fns ...AggregateFunc) *ForcastSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *ForcastSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ForcastQuery, *ForcastSelect](ctx, fs.ForcastQuery, fs, fs.inters, v)
}

func (fs *ForcastSelect) sqlScan(ctx context.Context, root *ForcastQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
