// Code generated by ent, DO NOT EDIT.

package ent

import (
	"g_api/libs/weather-lib/ent/forecast"
	"g_api/libs/weather-lib/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	forecastFields := schema.Forecast{}.Fields()
	_ = forecastFields
	// forecastDescCountry is the schema descriptor for country field.
	forecastDescCountry := forecastFields[0].Descriptor()
	// forecast.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	forecast.CountryValidator = forecastDescCountry.Validators[0].(func(string) error)
	// forecastDescTemp is the schema descriptor for temp field.
	forecastDescTemp := forecastFields[5].Descriptor()
	// forecast.DefaultTemp holds the default value on creation for the temp field.
	forecast.DefaultTemp = forecastDescTemp.Default.(float64)
}
