// Code generated by ent, DO NOT EDIT.

package ent

import (
	"g_api/libs/weather-lib/ent/forecast"
	"g_api/libs/weather-lib/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	forecastFields := schema.Forecast{}.Fields()
	_ = forecastFields
	// forecastDescCountry is the schema descriptor for country field.
	forecastDescCountry := forecastFields[0].Descriptor()
	// forecast.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	forecast.CountryValidator = forecastDescCountry.Validators[0].(func(string) error)
	// forecastDescMaxTemp is the schema descriptor for max_temp field.
	forecastDescMaxTemp := forecastFields[5].Descriptor()
	// forecast.DefaultMaxTemp holds the default value on creation for the max_temp field.
	forecast.DefaultMaxTemp = forecastDescMaxTemp.Default.(float64)
	// forecastDescMinTemp is the schema descriptor for min_temp field.
	forecastDescMinTemp := forecastFields[6].Descriptor()
	// forecast.DefaultMinTemp holds the default value on creation for the min_temp field.
	forecast.DefaultMinTemp = forecastDescMinTemp.Default.(float64)
	// forecastDescAvgTemp is the schema descriptor for avg_temp field.
	forecastDescAvgTemp := forecastFields[7].Descriptor()
	// forecast.DefaultAvgTemp holds the default value on creation for the avg_temp field.
	forecast.DefaultAvgTemp = forecastDescAvgTemp.Default.(float64)
}
