// Code generated by ent, DO NOT EDIT.

package ent

import (
	"g_api/libs/weather-lib/ent/forcast"
	"g_api/libs/weather-lib/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	forcastFields := schema.Forcast{}.Fields()
	_ = forcastFields
	// forcastDescCountry is the schema descriptor for country field.
	forcastDescCountry := forcastFields[0].Descriptor()
	// forcast.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	forcast.CountryValidator = forcastDescCountry.Validators[0].(func(string) error)
	// forcastDescMaxTemp is the schema descriptor for max_temp field.
	forcastDescMaxTemp := forcastFields[5].Descriptor()
	// forcast.DefaultMaxTemp holds the default value on creation for the max_temp field.
	forcast.DefaultMaxTemp = forcastDescMaxTemp.Default.(float64)
	// forcastDescMinTemp is the schema descriptor for min_temp field.
	forcastDescMinTemp := forcastFields[6].Descriptor()
	// forcast.DefaultMinTemp holds the default value on creation for the min_temp field.
	forcast.DefaultMinTemp = forcastDescMinTemp.Default.(float64)
	// forcastDescAvgTemp is the schema descriptor for avg_temp field.
	forcastDescAvgTemp := forcastFields[7].Descriptor()
	// forcast.DefaultAvgTemp holds the default value on creation for the avg_temp field.
	forcast.DefaultAvgTemp = forcastDescAvgTemp.Default.(float64)
}
