// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ForecastsColumns holds the columns for the "forecasts" table.
	ForecastsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "country", Type: field.TypeString, Size: 2147483647},
		{Name: "region", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "date", Type: field.TypeTime},
		{Name: "localtime", Type: field.TypeTime, Nullable: true},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "max_temp", Type: field.TypeFloat64, Default: 0},
		{Name: "min_temp", Type: field.TypeFloat64, Default: 0},
		{Name: "avg_temp", Type: field.TypeFloat64, Default: 0},
	}
	// ForecastsTable holds the schema information for the "forecasts" table.
	ForecastsTable = &schema.Table{
		Name:       "forecasts",
		Columns:    ForecastsColumns,
		PrimaryKey: []*schema.Column{ForecastsColumns[0]},
	}
	// WeathersColumns holds the columns for the "weathers" table.
	WeathersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "date", Type: field.TypeTime},
		{Name: "time", Type: field.TypeInt},
		{Name: "time_epoch", Type: field.TypeTime, Nullable: true},
		{Name: "temp", Type: field.TypeFloat64},
		{Name: "feels_like", Type: field.TypeFloat64},
		{Name: "forecast_weather", Type: field.TypeInt, Nullable: true},
	}
	// WeathersTable holds the schema information for the "weathers" table.
	WeathersTable = &schema.Table{
		Name:       "weathers",
		Columns:    WeathersColumns,
		PrimaryKey: []*schema.Column{WeathersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "weathers_forecasts_weather",
				Columns:    []*schema.Column{WeathersColumns[7]},
				RefColumns: []*schema.Column{ForecastsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ForecastsTable,
		WeathersTable,
	}
)

func init() {
	WeathersTable.ForeignKeys[0].RefTable = ForecastsTable
}
