// Code generated by ent, DO NOT EDIT.

package forecast

import (
	"g_api/libs/weather-lib/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Forecast {
	return predicate.Forecast(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Forecast {
	return predicate.Forecast(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Forecast {
	return predicate.Forecast(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Forecast {
	return predicate.Forecast(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Forecast {
	return predicate.Forecast(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Forecast {
	return predicate.Forecast(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Forecast {
	return predicate.Forecast(sql.FieldLTE(FieldID, id))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldCountry, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldRegion, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldDate, v))
}

// Localtime applies equality check predicate on the "localtime" field. It's identical to LocaltimeEQ.
func Localtime(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldLocaltime, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldIcon, v))
}

// Temp applies equality check predicate on the "temp" field. It's identical to TempEQ.
func Temp(v float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldTemp, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Forecast {
	return predicate.Forecast(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Forecast {
	return predicate.Forecast(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldContainsFold(FieldCountry, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.Forecast {
	return predicate.Forecast(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.Forecast {
	return predicate.Forecast(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionIsNil applies the IsNil predicate on the "region" field.
func RegionIsNil() predicate.Forecast {
	return predicate.Forecast(sql.FieldIsNull(FieldRegion))
}

// RegionNotNil applies the NotNil predicate on the "region" field.
func RegionNotNil() predicate.Forecast {
	return predicate.Forecast(sql.FieldNotNull(FieldRegion))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldContainsFold(FieldRegion, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldLTE(FieldDate, v))
}

// LocaltimeEQ applies the EQ predicate on the "localtime" field.
func LocaltimeEQ(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldLocaltime, v))
}

// LocaltimeNEQ applies the NEQ predicate on the "localtime" field.
func LocaltimeNEQ(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldNEQ(FieldLocaltime, v))
}

// LocaltimeIn applies the In predicate on the "localtime" field.
func LocaltimeIn(vs ...time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldIn(FieldLocaltime, vs...))
}

// LocaltimeNotIn applies the NotIn predicate on the "localtime" field.
func LocaltimeNotIn(vs ...time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldNotIn(FieldLocaltime, vs...))
}

// LocaltimeGT applies the GT predicate on the "localtime" field.
func LocaltimeGT(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldGT(FieldLocaltime, v))
}

// LocaltimeGTE applies the GTE predicate on the "localtime" field.
func LocaltimeGTE(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldGTE(FieldLocaltime, v))
}

// LocaltimeLT applies the LT predicate on the "localtime" field.
func LocaltimeLT(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldLT(FieldLocaltime, v))
}

// LocaltimeLTE applies the LTE predicate on the "localtime" field.
func LocaltimeLTE(v time.Time) predicate.Forecast {
	return predicate.Forecast(sql.FieldLTE(FieldLocaltime, v))
}

// LocaltimeIsNil applies the IsNil predicate on the "localtime" field.
func LocaltimeIsNil() predicate.Forecast {
	return predicate.Forecast(sql.FieldIsNull(FieldLocaltime))
}

// LocaltimeNotNil applies the NotNil predicate on the "localtime" field.
func LocaltimeNotNil() predicate.Forecast {
	return predicate.Forecast(sql.FieldNotNull(FieldLocaltime))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.Forecast {
	return predicate.Forecast(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.Forecast {
	return predicate.Forecast(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldHasSuffix(FieldIcon, v))
}

// IconIsNil applies the IsNil predicate on the "icon" field.
func IconIsNil() predicate.Forecast {
	return predicate.Forecast(sql.FieldIsNull(FieldIcon))
}

// IconNotNil applies the NotNil predicate on the "icon" field.
func IconNotNil() predicate.Forecast {
	return predicate.Forecast(sql.FieldNotNull(FieldIcon))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.Forecast {
	return predicate.Forecast(sql.FieldContainsFold(FieldIcon, v))
}

// TempEQ applies the EQ predicate on the "temp" field.
func TempEQ(v float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldEQ(FieldTemp, v))
}

// TempNEQ applies the NEQ predicate on the "temp" field.
func TempNEQ(v float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldNEQ(FieldTemp, v))
}

// TempIn applies the In predicate on the "temp" field.
func TempIn(vs ...float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldIn(FieldTemp, vs...))
}

// TempNotIn applies the NotIn predicate on the "temp" field.
func TempNotIn(vs ...float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldNotIn(FieldTemp, vs...))
}

// TempGT applies the GT predicate on the "temp" field.
func TempGT(v float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldGT(FieldTemp, v))
}

// TempGTE applies the GTE predicate on the "temp" field.
func TempGTE(v float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldGTE(FieldTemp, v))
}

// TempLT applies the LT predicate on the "temp" field.
func TempLT(v float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldLT(FieldTemp, v))
}

// TempLTE applies the LTE predicate on the "temp" field.
func TempLTE(v float64) predicate.Forecast {
	return predicate.Forecast(sql.FieldLTE(FieldTemp, v))
}

// HasWeather applies the HasEdge predicate on the "weather" edge.
func HasWeather() predicate.Forecast {
	return predicate.Forecast(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WeatherTable, WeatherColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWeatherWith applies the HasEdge predicate on the "weather" edge with a given conditions (other predicates).
func HasWeatherWith(preds ...predicate.Weather) predicate.Forecast {
	return predicate.Forecast(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(WeatherInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WeatherTable, WeatherColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Forecast) predicate.Forecast {
	return predicate.Forecast(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Forecast) predicate.Forecast {
	return predicate.Forecast(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Forecast) predicate.Forecast {
	return predicate.Forecast(func(s *sql.Selector) {
		p(s.Not())
	})
}
