name: Test
on: [ pull_request ]
jobs:
  test-affected:
    name: Run unit tests on affetced projects
    needs: planning-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          node-version: 16.10.0
          path: node_modules
          key: ${{ runner.os }}-build-cache-node-modules${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm run affected:test



