// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Forecast is the predicate function for forecast builders.
type Forecast func(*sql.Selector)

// Weather is the predicate function for weather builders.
type Weather func(*sql.Selector)
