// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Forcast is the predicate function for forcast builders.
type Forcast func(*sql.Selector)

// Weather is the predicate function for weather builders.
type Weather func(*sql.Selector)
